### ISSUE TITLE
logs are not overwritten

### ISSUE THREAD

**Issue by harschware** [intel-hadoop/Big-Bench#10]
The zipQuerylogs section in README states... Subsequent runs override the old log files. Maybe a bug, but log files do not get overwritten.  I believe they used to before the new kit was checked in.

**Comment by Manuel-Danisch** [comment]
Hi,

thanks for the hint. I removed the mentioned sentence from the README.md.

Best regards,
Manuel

**Comment by harschware** [comment]
It seem like it might be better to fix the scripts so that they wipe the logs and not append to them.   A few reasons:  1) that is the way it was before  2) it seems the whole reason to have the zipLogs feature is to guard against the erasure of the logs 3) appended logs maybe have less value?  It is really hard to tell when reading logs that are merge from multiple runs which run is doing what...   having a log file that can be a mixture of runs can lead to confusion and if the user is gathering data from the logs that stand a chance of getting mistaken data.

Finally, I'm not sure all the logs work in the same way:  So you end up with BigBenchResult.log not being appended copies, but individual queries are, and the inconsistency is confusing.

**Comment by tilmannrabl** [comment]
Hi Tim,

Thanks for the input, makes sense. We will consider it for the next update. 

Cheers,
Tilmann
