### ISSUE TITLE
Query 12 takes a very long time to finish (did not complete for a 2TB dataset)

### ISSUE THREAD

**Issue by nishkamravi2** [intel-hadoop/Big-Bench#16]

**Comment by Michael-Frank** [comment]
On which date/Gihub revision did you test this query? 
We reworked q12 on 6 Feb. 2015. So its important to know if this issue was with the old or the new version.

**Comment by harschware** [comment]
I've noticed failures with this query of the "Error: GC overhead limit exceeded" variety, when working with larger scale factors (e.g. 1000).  By default our clusters are set very low with:
mapreduce.map.memory.mb: 812
mapreduce.map.java.opts: -Xmx1024m
I have not had a chance to run this query whilst setting these values higher, but it may be helpful if the OP provided SF factor and memory settings.

**Comment by nishkamravi2** [comment]
I didn't have the latest version of this query from Feb 6th. Will run the new one soon and update this issue.

**Comment by XiaominZhang** [comment]
Please try with more recent Apache Hive e.g. 0.14 or 1.1 or CDH5.4. We also find this issue on Hive 0.13 (in CDH5.3).

**Comment by nishkamravi2** [comment]
Q12 is now going through (with latest Hive/query versions). Closing this issue.
