### ISSUE TITLE
Impossible to determine start/stop time of queries if run individually

### ISSUE THREAD

**Issue by harschware** [intel-hadoop/Big-Bench#9]
The patch below will modify the logs to produce a human friendly and parser friendly start and stop time.  Please apply it to runQuery script...

diff --git a/engines/hive/bin/runQuery b/engines/hive/bin/runQuery
index 1742418..2d43dd3 100644
--- a/engines/hive/bin/runQuery
+++ b/engines/hive/bin/runQuery
@@ -64,7 +64,9 @@ runModule () {
 
   # Run the main method implemented in the query's run.sh
   TIME_MEASUREMENT_FILE="`mktemp`"
-  echo "======= $TABLE_PREFIX time =========" > "$TIME_MEASUREMENT_FILE"
+  STARTAT=`date +%Y/%m/%d %H:%M:%S`
+  STARTAT_EPOCH=`date +%s` # seconds since epoch
+  echo "======= $TABLE_PREFIX time =========" $STARTAT $STARTAT_EPOCH  > "$TIME_MEASUREMENT_FILE"
   { time "$QUERY_MAIN_METHOD" > >(tee -a "$LOG_FILE_NAME") 2>&1 ; } 2>> "$TIME_MEASUREMENT_FILE"
   cat "$TIME_MEASUREMENT_FILE" >> "$LOG_FILE_NAME"
   rm -rf "$TIME_MEASUREMENT_FILE"
@@ -72,6 +74,8 @@ runModule () {
 
   echo "======= $TABLE_PREFIX result =======" | tee -a "$LOG_FILE_NAME" 2>&1
   echo "results in: $RESULT_DIR" | tee -a "$LOG_FILE_NAME" 2>&1
+  STOPAT=`date +%Y/%m/%d %H:%M:%S`
+  STOPAT_EPOCH=`date +%s` # seconds since epoch
   echo "to display: hadoop fs -cat $RESULT_DIR/*" | tee -a "$LOG_FILE_NAME" 2>&1
-  echo "=========================" | tee -a "$LOG_FILE_NAME" 2>&1
+  echo "=========================" $STOPAT $STOPAT_EPOCH | tee -a "$LOG_FILE_NAME" 2>&1
 }

**Comment by harschware** [comment]
Actually, it would be better if the human readable date were 'date +%Y/%m/%d:%H:%M:%S'.  We use that format for collectl metrics...

**Comment by Manuel-Danisch** [comment]
Hi,

thanks for your report. I'll take a look into this issue tomorrow.

Best regards,
Manuel

**Comment by Manuel-Danisch** [comment]
Hi,

I slightly changed the above patch. runQuery now adds two additional lines at the end of the log providing the requested timestamps.

Best regards,
Manuel
